### ISSUE TITLE
ImportError: No module named tools.manage

### ISSUE THREAD

**Issue by kenvifire** [oisinmulvihill/remarkable-friend#1]
Hi there,
I followed the README page to setup remarkable-friend, but when I ran `rmfriend sync`, I got error.
And this is the error message:
`Traceback (most recent call last):
  File "/usr/local/bin/rmfriend", line 11, in <module>
    load_entry_point('remarkable-friend', 'console_scripts', 'rmfriend')()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2691, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2322, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2328, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ImportError: No module named tools.manage`

Can you give me some hints about how to resolve it? I'll really appreciate it. And also great work for this tool!

Thanks,
Kenvi

**Comment by oisinmulvihill** [comment]
Hi Kenvi,

I don't use python2.7 only python3.6. This project was a way for me to get away from 2.7. Can you try running it on python3 instead?

**Comment by kenvifire** [comment]
Hi oisinmulvihill,

Python3.6 fixed this problem, thank you very much!

Thanks,
Kenvi
